# Generated by Django 2.1.4 on 2018-12-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jumuiyas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('jumuiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumuiyas.Jumuiya')),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
    ]
