# Generated by Django 2.1.4 on 2019-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
