# Generated by Django 2.1.4 on 2019-01-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
