# Generated by Django 2.1.4 on 2019-01-04 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('groups', '0001_initial'),
        ('jumuiyas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('YOUTH', 'YOUTH'), ('CHILDREN', 'CHILDREN')], max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('baptism', models.BooleanField(default=False)),
                ('eucharist', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('matrimony', models.BooleanField(default=False)),
                ('other_groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Family')),
                ('jumuiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumuiyas.Jumuiya')),
                ('main_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
    ]
