# Generated by Django 2.1.4 on 2019-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0002_auto_20190104_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='main_group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='other_groups',
        ),
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, to='groups.Group'),
        ),
    ]
