# Generated by Django 2.1.4 on 2019-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190109_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
